import { useRef, useState } from "react";

import {
  MantineProvider,
  Title,
  Header,
  Flex,
  Navbar,
  AppShell,
  NavLink,
  Burger,
  MediaQuery,
} from "@mantine/core";
import { useMediaQuery } from "@mantine/hooks";
import {
  IconBrandGithub,
  IconBriefcase,
  IconSchool,
  IconTools,
  IconUser,
} from "@tabler/icons";
import Head from "next/head";

import {
  AboutCard,
  ProjectCard,
  SchoolCard,
  SkillCard,
  WorkCard,
} from "../components";
import { about, skills, projects, schooling, work } from "../data";
import styles from "../styles/Home.module.css";

export default function Home() {
  const aboutRef = useRef<HTMLDivElement>(null);
  const workRef = useRef<HTMLHeadingElement>(null);
  const schoolRef = useRef<HTMLHeadingElement>(null);
  const projectsRef = useRef<HTMLHeadingElement>(null);
  const skillRef = useRef<HTMLHeadingElement>(null);

  const [opened, setOpened] = useState(false);

  const isSmallScreen = useMediaQuery("(max-width: 900px)");

  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <div className={styles.container}>
        <Head>
          <title>Adam Schlichtmann</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={styles.main}>
          <AppShell
            padding='md'
            navbar={
              <Navbar
                width={{
                  md: 300,
                }}
                hidden={!opened}
              >
                <Navbar.Section>
                  <NavLink
                    label='About Me'
                    icon={<IconUser />}
                    onClick={() => {
                      aboutRef.current?.scrollIntoView({
                        behavior: "smooth",
                        block: "center",
                      });
                      if (isSmallScreen) {
                        setOpened(false);
                      }
                    }}
                  />
                </Navbar.Section>
                <Navbar.Section>
                  <NavLink
                    label='Work'
                    icon={<IconBriefcase />}
                    onClick={() => {
                      workRef.current?.scrollIntoView({
                        behavior: "smooth",
                        block: "center",
                      });
                      if (isSmallScreen) {
                        setOpened(false);
                      }
                    }}
                  />
                </Navbar.Section>
                <Navbar.Section>
                  <NavLink
                    label='School'
                    icon={<IconSchool />}
                    onClick={() => {
                      schoolRef.current?.scrollIntoView({
                        behavior: "smooth",
                        block: "center",
                      });
                      if (isSmallScreen) {
                        setOpened(false);
                      }
                    }}
                  />
                </Navbar.Section>
                <Navbar.Section>
                  <NavLink
                    label='Projects'
                    icon={<IconBrandGithub />}
                    onClick={() => {
                      projectsRef.current?.scrollIntoView({
                        behavior: "smooth",
                        block: "center",
                      });
                      if (isSmallScreen) {
                        setOpened(false);
                      }
                    }}
                  />
                </Navbar.Section>
                <Navbar.Section>
                  <NavLink
                    label='Skill'
                    icon={<IconTools />}
                    onClick={() => {
                      skillRef.current?.scrollIntoView({
                        behavior: "smooth",
                        block: "center",
                      });
                      if (isSmallScreen) {
                        setOpened(false);
                      }
                    }}
                  />
                </Navbar.Section>
              </Navbar>
            }
            header={
              <Header height={{ base: 100 }} p='md'>
                <Flex direction={"row"} align='center'>
                  <MediaQuery largerThan='md' styles={{ display: "none" }}>
                    <Burger
                      opened={opened}
                      onClick={() => setOpened((o) => !o)}
                      size='sm'
                      mr='xl'
                    />
                  </MediaQuery>
                  <Title align='center' mt='sm' mb='sm'>
                    Adam Schlichtmann
                  </Title>
                </Flex>
              </Header>
            }
          >
            <Flex direction='column' gap='xl'>
              <AboutCard me={about} ref={aboutRef} />
              <Title order={2} align='center' mt='xl' mb='md' ref={workRef}>
                Work Experience
              </Title>
              {work.map((work) => (
                <WorkCard key={`${work.title}-${work.company}`} work={work} />
              ))}
              <Title order={2} align='center' mt='xl' mb='md' ref={schoolRef}>
                School
              </Title>
              {schooling.map((school) => (
                <SchoolCard key={school.degree} school={school} />
              ))}

              <Title order={2} align='center' mt='xl' mb='md' ref={projectsRef}>
                Projects
              </Title>
              {projects.map((project) => (
                <ProjectCard key={project.name} project={project} />
              ))}
              <Title order={2} align='center' mt='xl' mb='md' ref={skillRef}>
                Skills
              </Title>
              {skills.map((skill) => (
                <SkillCard key={skill.name} skill={skill} />
              ))}
            </Flex>
          </AppShell>
        </main>
      </div>
    </MantineProvider>
  );
}
