import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LanguageCard from "./components/LanguageCard";
import WorkExperience from "./components/WorkExperience";

import { work } from "./data/work";

import { Grid, MantineProvider, Space, Title } from "@mantine/core";
import { language } from "./data/language";
import About from "./components/About";
import { about } from "./data/about";
import { school } from "./data/school";
import School from "./components/School";
import { projects } from "./data/project";
import Project from "./components/Project";

export default function Home() {
  return (
    <MantineProvider withGlobalStyles withNormalizeCSS>
      <div className={styles.container}>
        <Head>
          <title>Adam Schlichtmann</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <main className={styles.main}>
          <Grid gutter='xl'>
            <Grid.Col xs={1} sm={1} md={3} lg={6} xl={6}>
              <About me={about} />
              <Title order={2} align='center' mt='xl' mb='md'>
                Work Experience
              </Title>
              {work.map((job) => (
                <WorkExperience
                  key={`${job.title}-${job.company}`}
                  title={job.title}
                  company={job.company}
                  description={job.description}
                  badges={job.badges}
                  start={job.startDate}
                  end={job.endDate}
                />
              ))}
              <Title order={2} align='center' mt='xl' mb='md'>
                School
              </Title>
              {school.map((cool) => (
                <School key={cool.degree} school={cool} />
              ))}
              <Title order={2} align='center' mt='xl' mb='md'>
                Projects
              </Title>
              {projects.map((project) => (
                <Project key={project.name} project={project} />
              ))}
              <Title order={2} align='center' mt='xl' mb='md'>
                Skills
              </Title>
              {language.map((lang) => (
                <LanguageCard
                  key={lang.name}
                  language={lang.name}
                  percent={lang.confidence}
                />
              ))}
            </Grid.Col>
          </Grid>
        </main>
      </div>
    </MantineProvider>
  );
}
