import { useRef, useState } from "react";

import {
  MantineProvider,
  Title,
  Header,
  Flex,
  Navbar,
  AppShell,
  Burger,
  MediaQuery,
} from "@mantine/core";
import {
  IconBrandGithub,
  IconBriefcase,
  IconSchool,
  IconTools,
  IconUser,
} from "@tabler/icons";
import Head from "next/head";

import {
  AboutCard,
  CustomNavLink,
  ProjectCard,
  SchoolCard,
  SkillCard,
  WorkCard,
} from "../components";
import { about, skills, projects, schooling, work } from "../data";
import styles from "../styles/Home.module.css";

export default function Home() {
  const aboutRef = useRef<HTMLDivElement>(null);
  const workRef = useRef<HTMLHeadingElement>(null);
  const schoolRef = useRef<HTMLHeadingElement>(null);
  const projectsRef = useRef<HTMLHeadingElement>(null);
  const skillRef = useRef<HTMLHeadingElement>(null);

  const [opened, setOpened] = useState(false);

  return (
    <MantineProvider
      withGlobalStyles
      withNormalizeCSS
      theme={{
        primaryColor: "cyan",
      }}
    >
      <div className={styles.container}>
        <Head>
          <title>Adam Schlichtmann</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <main className={styles.main}>
          <AppShell
            styles={(theme) => ({
              body: {
                backgroundColor: theme.colors.gray[2],
              },
            })}
            padding='md'
            navbar={
              <Navbar
                width={{
                  md: 300,
                }}
                hidden={!opened}
                sx={(theme) => ({
                  backgroundColor: theme.colors.gray[4],
                })}
              >
                <CustomNavLink
                  label='About Me'
                  icon={<IconUser />}
                  ref={aboutRef}
                  setOpened={setOpened}
                />
                <CustomNavLink
                  label='Work'
                  icon={<IconBriefcase />}
                  ref={workRef}
                  setOpened={setOpened}
                />
                <CustomNavLink
                  label='School'
                  icon={<IconSchool />}
                  ref={schoolRef}
                  setOpened={setOpened}
                />
                <CustomNavLink
                  label='Projects'
                  icon={<IconBrandGithub />}
                  ref={projectsRef}
                  setOpened={setOpened}
                />
                <CustomNavLink
                  label='Skill'
                  icon={<IconTools />}
                  ref={skillRef}
                  setOpened={setOpened}
                />
              </Navbar>
            }
            header={
              <Header
                height={{ base: 100 }}
                p='md'
                sx={(theme) => ({
                  backgroundColor: theme.colors.teal[3],
                })}
              >
                <Flex direction='row' align='center'>
                  <MediaQuery largerThan='md' styles={{ display: "none" }}>
                    <Burger
                      opened={opened}
                      onClick={() => setOpened((o) => !o)}
                      size='sm'
                      mr='xl'
                    />
                  </MediaQuery>
                  <Title align='center' mt='sm' mb='sm'>
                    Adam Schlichtmann
                  </Title>
                </Flex>
              </Header>
            }
          >
            <Flex direction='column' gap='xl'>
              <AboutCard me={about} ref={aboutRef} />
              <Title order={2} align='center' mt='xl' mb='md' ref={workRef}>
                Work Experience
              </Title>
              {work.map((work) => (
                <WorkCard key={`${work.title}-${work.company}`} work={work} />
              ))}
              <Title order={2} align='center' mt='xl' mb='md' ref={schoolRef}>
                School
              </Title>
              {schooling.map((school) => (
                <SchoolCard key={school.degree} school={school} />
              ))}
              <Title order={2} align='center' mt='xl' mb='md' ref={projectsRef}>
                Projects
              </Title>
              {projects.map((project) => (
                <ProjectCard key={project.name} project={project} />
              ))}
              <Title order={2} align='center' mt='xl' mb='md' ref={skillRef}>
                Skills
              </Title>
              {skills.map((skill) => (
                <SkillCard key={skill.name} skill={skill} />
              ))}
            </Flex>
          </AppShell>
        </main>
      </div>
    </MantineProvider>
  );
}
